name: app
type: "php:8"
disk: 1024

dependencies:
    php:
        composer/composer: '^2.0'

hooks:
    build: |
        composer --version

web:
    locations:
        /:
            root: web
            passthru: true
